# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [115]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A)
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
15
int32


In [6]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
Z = array_3d
print(Z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [18]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()
print(B @ C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [17]:
print(B - C)
print()
print(B * C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [22]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [117]:
print(np.exp(B))
print()
print('Minsta värdet =', np.min(B))
print()
print('Minsta värdet i varje rad', np.min(B, axis = 0))
print()
print('Minsta värdet i varje column', np.min(B, axis = 1 ))
print()
print('Index värdet för minsta värdet i hela matrisen', np.argmin(B))
print()
print('Index värdet för minsta värdet i varje rad', np.argmin(B, axis = 0))
print()
print('Summan av alla element', B.sum() )
print()
print('Räkna ut medlevärde för varje column',np.mean(B, axis = 1))
print()
print('räkna ut medianen för varje column', np.median(B, axis = 1))

[[ 7.3890561   2.71828183]
 [ 2.71828183 20.08553692]]

Minsta värdet = 1

Minsta värdet i varje rad [1 1]

Minsta värdet i varje column [1 1]

Index värdet för minsta värdet i hela matrisen 1

Index värdet för minsta värdet i varje rad [1 0]

Summan av alla element 7

Räkna ut medlevärde för varje column [1.5 2. ]

räkna ut medianen för varje column [1.5 2. ]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [41]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [51]:
# print(A[1])
A[0]

array([1, 2, 3, 4, 5])

**Answer:**

In [44]:
# You only get the axes which the index number you used represents. All the other axis are kept intact.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [54]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [55]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [56]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [126]:
a = np.arange(30)
b = a.reshape((2, 3,-1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [8]:
# It means that each matrix has 3 rows

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [17]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [18]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [19]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [128]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [134]:
def add_mult_matrices(A, B, add_or_multiply):
    if not(isinstance(A, np.ndarray)and isinstance(B, np.ndarray)):
        raise Exeption('You have to use 2 matrices!')
    if add_or_multiply == 'add':
        if  A.shape != B.shape:
            raise Exception('The matrices have to be the same shape for matrix addition')
        else:
            return A + B           
    
    if add_or_multiply == 'multiply':
        if A.shape[1] != B.shape[0]:
            raise Exception('Columns in the fist matrix must have the same lenght as the rows in the second matrix!')
        else:
            return A @ B
    else:
        raise('You must use "add" or "multiply!" ')
    


In [130]:
# B-2A
add_mult_matrices(B,-2*A, 'add')

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [135]:
# 3C-E
add_mult_matrices(3*C, -E, 'add')

Exception: The matrices have to be the same shape for matrix addition

In [136]:
# A*C
add_mult_matrices(A, C, 'multiply')

Exception: Columns in the fist matrix must have the same lenght as the rows in the second matrix!

In [132]:
# C*D
add_mult_matrices(C, D, 'multiply')

array([[11, 10],
       [10, 11]])

In [133]:
# C*B
add_mult_matrices(C, B, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [80]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [85]:
x =add_mult_matrices(A, B, 'multiply')
y =add_mult_matrices(A, C, 'multiply')

print('AB: ')
print(x)
print('AC: ')
print(y)

print(x==y)
print(B==C)

AB: 
[[ 4  7]
 [ 8 14]]
AC: 
[[ 4  7]
 [ 8 14]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


**Chap2. Question 3**

In [86]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [89]:
AD= add_mult_matrices(A, D,'multiply')
DA= add_mult_matrices(D, A,'multiply')

print('AD:','\n', AD)
print('DA:', '\n', DA)

AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA: 
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [92]:
x = np.array([[1, -1], [-1, 1]])
y = np.array([[-1, 1], [1, -1]])

In [93]:
answer = add_mult_matrices(x,y, 'multiply')

print(answer)

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [96]:
x = np.array([[5, 6], [4, 5]])
y = np.array([[6, 4], [3, 3]])

In [98]:
x_invers = np.linalg.inv(x)
y_invers= np.linalg.inv(y)
print('Invers of x:', '\n' ,x_invers)
print('Invers of y:', '\n' ,y_invers)

Invers of x: 
 [[ 5. -6.]
 [-4.  5.]]
Invers of y: 
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [100]:
x = np.array([[2,2], [1,2]])

In [101]:
x_inv = np.linalg.inv(x)

print('Invers of x:', '\n' ,x_inv)

Invers of x: 
 [[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [102]:
x = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
y = np.array([-7, 5, 2])

In [103]:
solution= np.linalg.solve(x,y)
print(solution)

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [104]:
x = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
y = np.array([1, -1, 1])

In [105]:
solution = np.linalg.solve(x,y)

print(solution)

[ 8.  2. -1.]


**Chap 12. Question 1**

In [106]:
x = np.array([[3, -7, -2],[-3, 5, 1],[6, -4,0]])

In [111]:
x_inv = np.linalg.inv(x)

print(x_inv)


[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [112]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [113]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [114]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
